spring:
  jpa.hibernate.ddl-auto: update  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videoclub
    username: root
    password: toor
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      
server:
  port: 8081

logging:
    level:
        es.iesjandula: info
    file:
      name: C:/logs/Issues.log
      max-size: 1MB
      max-history: 10
      total-size-cap: 10MB
